import { create } from 'zustand';

export interface TemplateItem {
    id: string;
    file_name: string;
    file_path: string; // Could be a file path, a URL, or text snippet content
    file_ext: string;  // pdf, png, docx, dwg, txt, link, etc.
    file_size?: number;
    import_date: string;
    
    // Dynamic category generated by AI, or "Uncategorized" by default
    category: string;
    tags: string[];
    
    // AI 分析结果
    ai_status: 'pending' | 'processing' | 'success' | 'failed' | 'unsupported';
    ai_summary?: string;     // 关键大体综述内容
    ai_raw_text?: string;    // 从文件中提取的原始文本(全文字段提取保留)
}

interface TemplateState {
    templates: TemplateItem[];
    setTemplates: (templates: TemplateItem[]) => void;
    addTemplate: (template: TemplateItem) => void;
    updateTemplate: (template: TemplateItem) => void;
    deleteTemplate: (id: string) => void;
}

export const useTemplateStore = create<TemplateState>((set) => ({
    templates: [],
    setTemplates: (templates) => set({ templates }),
    addTemplate: (template) => set((state) => ({ templates: [template, ...state.templates] })),
    updateTemplate: (updated) => set((state) => ({
        templates: state.templates.map((t) => t.id === updated.id ? updated : t)
    })),
    deleteTemplate: (id) => set((state) => ({
        templates: state.templates.filter((t) => t.id !== id)
    })),
}));
